
-- Table for ELITE demo licenses generated by DEMOADM
CREATE TABLE public.demo_licenses (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  nome TEXT NOT NULL,
  whatsapp TEXT,
  email TEXT,
  cidade TEXT,
  senha TEXT NOT NULL UNIQUE,
  validade_dias INTEGER NOT NULL DEFAULT 7,
  data_envio TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  data_expiracao TIMESTAMP WITH TIME ZONE NOT NULL,
  status TEXT NOT NULL DEFAULT 'Ativo',
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- RLS: only edge functions (service role) can read/write
ALTER TABLE public.demo_licenses ENABLE ROW LEVEL SECURITY;

-- No public policies - accessed only via edge functions with service role
