// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const checkUseLocalProxy = () => {
  if (typeof window === "undefined") return false;
  const hn = window.location.hostname;
  return (
    import.meta.env.DEV ||
    hn.includes("run.app") ||
    hn.includes("localhost") ||
    hn.includes("127.0.0.1") ||
    hn.includes("google") ||
    hn.includes("aistudio")
  );
};

const SUPABASE_URL = checkUseLocalProxy()
  ? window.location.origin
  : import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});